import { code, describeNode } from "./markdown.js";
import { toMermaid } from "./mermaid.js";
import type { KindStyle } from "./config.js";
import type { ArchitectureModel } from "./model.js";

/**
 * Hidden marker placed at the top of every architecture document. Marks the file as
 * generated, so a reader — or a script — knows not to edit it by hand.
 */
export const ARCHITECTURE_MARKER = "<!-- trazo-architecture -->";

/**
 * Renders a full snapshot of an architecture model as a Markdown document, meant to be kept as
 * a file such as `ARCHITECTURE.md` and regenerated whenever the underlying infrastructure files
 * change (see `trazo generate --format markdown`). Unlike {@link renderDiffMarkdown}, this has
 * no notion of a previous revision: it always describes `model` in full.
 *
 * The document always starts with {@link ARCHITECTURE_MARKER}.
 *
 * @param options.kinds - How to draw each kind of component, as in {@link toMermaid}.
 * @param options.command - The command that regenerates this very file, quoted in the header so a
 * reader knows how to update it. Defaults to one that writes `ARCHITECTURE.md`, which is only right
 * when that is where the document is going; a command containing a backtick is ignored.
 */
export function renderArchitectureMarkdown(
  model: ArchitectureModel,
  options: { kinds?: Readonly<Record<string, Partial<KindStyle>>>; command?: string } = {},
): string {
  const { kinds } = options;
  const command =
    options.command && !options.command.includes("`")
      ? options.command
      : "trazo generate --format markdown --out ARCHITECTURE.md";
  const lines = [
    ARCHITECTURE_MARKER,
    "# Architecture",
    "",
    `Generated by [Trazo](https://github.com/edgaragg/trazo) from this repository's infrastructure files. Do not edit by hand — regenerate it with \`${command}\`.`,
    "",
  ];

  if (model.nodes.length === 0) {
    lines.push("No supported infrastructure files were found.");
    return lines.join("\n");
  }

  lines.push("```mermaid", toMermaid(model, { ...(kinds && { kinds }) }), "```", "", "## Components", "");
  for (const node of model.nodes) lines.push(`- ${describeNode(node)}`);

  if (model.edges.length > 0) {
    lines.push("", "## Dependencies", "");
    const names = new Map(model.nodes.map((node) => [node.id, node.name]));
    const label = (id: string) => code(names.get(id) ?? id);
    for (const edge of model.edges) lines.push(`- ${label(edge.from)} → ${label(edge.to)}`);
  }
  return lines.join("\n");
}
